version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: video-calling-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

